/* phenotype-gfx C-ABI header — auto-generated by cbindgen */

#ifndef PHENOTYPE_GFX_H
#define PHENOTYPE_GFX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Schema version of the public `phenotype-voxel` types. Bumped on breaking changes
 * so consumers can detect API drift in `.civreplay` / serialized voxel diffs.
 */
#define SCHEMA_VERSION 1

/**
 * Default `VoxelScaleMultiplier` derived from WSM3D's hard-won visible-default lesson
 * (mesh-local 11x5x1 ✕ sprite-scale 0.1 ≈ ~1.1x0.5x0.1 world → invisible; multiplier
 * of 8 brought it back to a usable rendered scale).
 */
#define DEFAULT_VOXEL_SCALE_MULTIPLIER 8.0

/**
 * Dense leaf chunks are always 16 voxels on a side; total `16^3 = 4096` voxels.
 */
#define CHUNK_EDGE 16

/**
 * Total voxels in a dense leaf chunk.
 */
#define CHUNK_VOXELS ((CHUNK_EDGE * CHUNK_EDGE) * CHUNK_EDGE)

/**
 * Fixed-point scale: `10^6`. World coords are `i64` numerators over this denominator.
 */
#define FIXED_SCALE 1000000

/**
 * Alpha threshold below which a pixel is considered transparent ("air").
 * WSM3D uses 16 / 255; we adopt the same constant.
 */
#define ALPHA_THRESHOLD 16

/**
 * Default extrusion depth when none is provided by the caller.
 * Mirrors `SpriteVoxelizer.DefaultDepth = 8` in WSM3D.
 */
#define DEFAULT_DEPTH 8

/**
 * Current schema version.
 */
#define SimLodAggregator_SCHEMA_VERSION 1

/**
 * Maximum number of chunks to prefetch per frame.
 */
#define DEFAULT_PREFETCH_BUDGET 4

/**
 * Stable, hashable identifier for a chunk in the world. Encodes chunk-grid
 * coordinates as a single `u64` so it can be used as a deterministic key without
 * committing to a particular `HashMap` iteration order.
 */
typedef struct ChunkId ChunkId;

/**
 * Per-cohort totals fed to the gestalt aggregator.
 */
typedef struct CohortTotals CohortTotals;

/**
 * World-extent budget.
 */
typedef struct ExtentBudget ExtentBudget;

/**
 * A gestalt summary — per-tick output of [`SimLodAggregator::fold`].
 */
typedef struct Gestalt Gestalt;

/**
 * Opaque handle returned to C callers for a `MaterialPalette`.
 */
typedef struct MaterialPaletteHandle MaterialPaletteHandle;

/**
 * Opaque handle returned to C callers for a `MeshBuffer`.
 */
typedef struct MeshBufferHandle MeshBufferHandle;

/**
 * Engine-neutral vertex layout. PBR-suitable: position + normal + uv + material slot.
 */
typedef struct MeshVertex MeshVertex;

/**
 * The MVP resident budget — validates a streaming config against MVP targets.
 */
typedef struct MvpResidentBudget MvpResidentBudget;

/**
 * MVP resident working set constants.
 */
typedef struct MvpResidentConfig MvpResidentConfig;

/**
 * Quality settings — the driver passes the current value to each pass.
 */
typedef struct PassQuality PassQuality;

/**
 * All post-fx configuration. Engine-agnostic: carries only logical state,
 * not Unity references.
 */
typedef struct PostStackConfig PostStackConfig;

/**
 * Sim-LOD gestalt aggregator — folds per-cohort totals deterministically.
 */
typedef struct SimLodAggregator SimLodAggregator;

/**
 * Opaque handle returned to C callers for a `StreamingManager`.
 */
typedef struct StreamingManagerHandle StreamingManagerHandle;

/**
 * Opaque handle returned to C callers for a `VoxelWorld<u8>`.
 */
typedef struct VoxelWorldHandle VoxelWorldHandle;



























#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new empty voxel world.
 *
 * `voxel_span` is the fixed-point size of one voxel edge (use `1_000_000` for
 * the standard 1 m voxel).
 *
 * Returns an opaque handle, or null on allocation failure.
 *
 * # Safety
 *
 * The returned handle must be destroyed with `phenotype_gfx_voxel_destroy`.
 */
struct VoxelWorldHandle *phenotype_gfx_voxel_create(int64_t voxel_span);

/**
 * Destroy a voxel world and release all associated memory.
 *
 * # Safety
 *
 * `handle` must have been returned by `phenotype_gfx_voxel_create` and must
 * not have been destroyed previously. Passing null is a no-op.
 */
void phenotype_gfx_voxel_destroy(struct VoxelWorldHandle *handle);

/**
 * Write a voxel value at the given world coordinate.
 *
 * `handle`, `x`, `y`, `z`, `value` are all consumed by value. The
 * containing chunk is lazily allocated. Idempotent writes are safe (no
 * dirty event emitted).
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_create`.
 */
void phenotype_gfx_voxel_set(struct VoxelWorldHandle *handle,
                             int64_t x,
                             int64_t y,
                             int64_t z,
                             uint8_t value);

/**
 * Read the voxel value at the given world coordinate.
 *
 * Returns the stored value, or `0` (default) if the coordinate is unmapped.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_create`.
 */
uint8_t phenotype_gfx_voxel_get(const struct VoxelWorldHandle *handle,
                                int64_t x,
                                int64_t y,
                                int64_t z);

/**
 * Return the number of allocated dense chunks in the world.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_create`.
 */
uint32_t phenotype_gfx_voxel_chunk_count(const struct VoxelWorldHandle *handle);

/**
 * Build a greedy mesh for chunk at chunk-grid coordinate `(cx, cy, cz)`.
 *
 * Returns an opaque `MeshBufferHandle`, or null if the chunk does not exist
 * or the mesher fails.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_create`.
 */
struct MeshBufferHandle *phenotype_gfx_voxel_mesh_build(const struct VoxelWorldHandle *handle,
                                                        int32_t cx,
                                                        int32_t cy,
                                                        int32_t cz);

/**
 * Destroy a mesh buffer and release its memory.
 *
 * # Safety
 *
 * `handle` must have been returned by `phenotype_gfx_voxel_mesh_build` and
 * not have been destroyed previously. Null is a no-op.
 */
void phenotype_gfx_voxel_mesh_destroy(struct MeshBufferHandle *handle);

/**
 * Return a pointer to the vertex data buffer.
 *
 * The returned pointer is valid for as long as the `MeshBufferHandle` is
 * alive. Each vertex is 32 bytes (3×f32 position + 3×f32 normal + 2×f32 uv
 * + 1×u16 material = 32 bytes packed).
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_mesh_build`.
 * The pointer is valid until `phenotype_gfx_voxel_mesh_destroy` is called.
 */
const struct MeshVertex *phenotype_gfx_voxel_vertices(const struct MeshBufferHandle *handle);

/**
 * Return a pointer to the triangle-index buffer.
 *
 * Indices are `u32`; every 3 indices form one triangle. The pointer is valid
 * for as long as the `MeshBufferHandle` is alive.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_mesh_build`.
 */
const uint32_t *phenotype_gfx_voxel_indices(const struct MeshBufferHandle *handle);

/**
 * Return the number of vertices in the mesh buffer.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_mesh_build`.
 */
uint32_t phenotype_gfx_voxel_vertex_count(const struct MeshBufferHandle *handle);

/**
 * Return the number of indices in the mesh buffer.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_voxel_mesh_build`.
 */
uint32_t phenotype_gfx_voxel_index_count(const struct MeshBufferHandle *handle);

/**
 * Create a new empty material palette.
 *
 * Returns an opaque handle, or null on allocation failure.
 *
 * # Safety
 *
 * The returned handle must be destroyed with `phenotype_gfx_material_destroy`.
 */
struct MaterialPaletteHandle *phenotype_gfx_material_create(void);

/**
 * Destroy a material palette and release its memory.
 *
 * # Safety
 *
 * `handle` must have been returned by `phenotype_gfx_material_create` and
 * not have been destroyed previously. Null is a no-op.
 */
void phenotype_gfx_material_destroy(struct MaterialPaletteHandle *handle);

/**
 * Add a material with the given `name` C-string and `hardness`.
 *
 * Returns the newly-assigned `MaterialId` as a `u16`, or `u16::MAX` on
 * overflow (palette full).
 *
 * # Safety
 *
 * - `handle` must be a valid, non-null pointer from `phenotype_gfx_material_create`.
 * - `name` must be a valid, null-terminated C string for the duration of
 *   this call. The string is copied internally; the caller retains ownership.
 */
uint16_t phenotype_gfx_material_set_property(struct MaterialPaletteHandle *handle,
                                             const char *name,
                                             float hardness);

/**
 * Look up a material by `id` and write its `hardness` into `*out_hardness`.
 *
 * Returns `1` on success, `0` if the id is not found.
 *
 * # Safety
 *
 * - `handle` must be a valid, non-null pointer from `phenotype_gfx_material_create`.
 * - `out_hardness` must be a valid, non-null `*mut f32`.
 */
int32_t phenotype_gfx_material_get_property(const struct MaterialPaletteHandle *handle,
                                            uint16_t id,
                                            float *out_hardness);

/**
 * Return the number of materials in the palette.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_material_create`.
 */
uint32_t phenotype_gfx_material_count(const struct MaterialPaletteHandle *handle);

/**
 * Create a new streaming manager.
 *
 * Returns an opaque handle, or null on allocation failure.
 *
 * # Safety
 *
 * The returned handle must be destroyed with `phenotype_gfx_streaming_destroy`.
 */
struct StreamingManagerHandle *phenotype_gfx_streaming_create(void);

/**
 * Destroy a streaming manager and release its memory.
 *
 * # Safety
 *
 * `handle` must have been returned by `phenotype_gfx_streaming_create` and
 * not have been destroyed previously. Null is a no-op.
 */
void phenotype_gfx_streaming_destroy(struct StreamingManagerHandle *handle);

/**
 * Load a chunk at chunk-grid coordinate `(cx, cy, cz)` into the streaming set.
 *
 * Returns a monotonic load-id (`> 0`) on success, or `0` if already loaded.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_streaming_create`.
 */
uint32_t phenotype_gfx_streaming_load(struct StreamingManagerHandle *handle,
                                      int32_t cx,
                                      int32_t cy,
                                      int32_t cz);

/**
 * Unload (remove) a chunk at chunk-grid coordinate `(cx, cy, cz)`.
 *
 * Returns `1` if the chunk was loaded and removed, `0` if it was not present.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_streaming_create`.
 */
int32_t phenotype_gfx_streaming_unload(struct StreamingManagerHandle *handle,
                                       int32_t cx,
                                       int32_t cy,
                                       int32_t cz);

/**
 * Return the number of currently loaded chunks.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_streaming_create`.
 */
uint32_t phenotype_gfx_streaming_loaded_count(const struct StreamingManagerHandle *handle);

/**
 * Evict the oldest (least-recently-loaded) chunk from the streaming set.
 *
 * Returns `1` if a chunk was evicted, `0` if the set is empty.
 *
 * # Safety
 *
 * `handle` must be a valid, non-null pointer from `phenotype_gfx_streaming_create`.
 */
int32_t phenotype_gfx_streaming_evict_oldest(struct StreamingManagerHandle *handle);

/**
 * Initialise the observability subsystem (no-op when no recorder is installed).
 *
 * Safe to call multiple times; subsequent calls are idempotent.
 */
void phenotype_gfx_obs_init(void);

/**
 * Increment the global observability counter by `delta`.
 *
 * # Safety
 *
 * No pointer safety requirements; this function is pure.
 */
void phenotype_gfx_obs_counter_inc(uint32_t delta);

/**
 * Set the global observability gauge to `value`.
 *
 * This writes to a static `AtomicU32` reinterpreted as a gauge (raw bits).
 * Consumers that need floating-point gauges should use the metrics facade
 * directly from Rust.
 *
 * # Safety
 *
 * No pointer safety requirements; this function is pure.
 */
void phenotype_gfx_obs_gauge_set(uint32_t value);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PHENOTYPE_GFX_H */
